In [4]:
import pandas as pd

# Problem 1

In [24]:
dataset = pd.read_csv("student_performance.csv")

# Problem 2

In [10]:
dataset.head()

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
0,S001,Ali Khan,20,AI,85,78,92,88,95
1,S002,Sara Ahmed,21,AI,72,75,70,80,90
2,S003,Ahmed Raza,22,SE,90,88,91,93,96
3,S004,Fatima Noor,20,DS,65,70,68,72,85
4,S005,Usman Ali,21,AI,78,82,80,76,88

In [13]:
dataset.tail()

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
15,S016,Hira Shah,21,DS,89,91,88,90,96
16,S017,Omar Farooq,20,AI,74,72,76,78,84
17,S018,Laiba Khan,22,SE,97,95,98,99,100
18,S019,Abdullah,21,DS,68,66,70,72,80
19,S020,Mehwish,20,AI,86,89,87,90,93

# Problem 3

In [14]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        20 non-null     str
 1   Name              20 non-null     str
 2   Age               20 non-null     int64
 3   Program           20 non-null     str
 4   Python            20 non-null     int64
 5   Mathematics       20 non-null     int64
 6   Statistics        20 non-null     int64
 7   Machine_Learning  20 non-null     int64
 8   Attendance        20 non-null     int64
dtypes: int64(6), str(3)
memory usage: 1.5 KB

# Probelm 4 - finding missing values

In [20]:
dataset.isna()

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False

In [ ]:
dataset.isna().sum() # missing values count in each column

Student_ID          0
Name                0
Age                 0
Program             0
Python              0
Mathematics         0
Statistics          0
Machine_Learning    0
Attendance          0
dtype: int64

# Problem 5

In [29]:
# filtering based on condition
# attendace > 90
dataset = dataset.loc[dataset['Attendance'] > 90]

In [30]:
dataset

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
0,S001,Ali Khan,20,AI,85,78,92,88,95
2,S003,Ahmed Raza,22,SE,90,88,91,93,96
5,S006,Ayesha Malik,22,SE,95,94,96,97,99
7,S008,Zainab Iqbal,21,AI,88,86,90,91,94
9,S010,Maryam Khan,20,DS,81,84,79,85,91
11,S012,Noor Fatima,21,SE,92,90,93,95,98
13,S014,Iqra Aslam,22,AI,84,83,86,88,92
15,S016,Hira Shah,21,DS,89,91,88,90,96
17,S018,Laiba Khan,22,SE,97,95,98,99,100
19,S020,Mehwish,20,AI,86,89,87,90,93

# Problem 6

In [31]:
# summary statistics of new filtered dataset 
dataset.describe()

,Age,Python,Mathematics,Statistics,Machine_Learning,Attendance
count,10.000000,10.00000,10.000000,10.000000,10.000000,10.000000
mean,21.100000,88.70000,87.800000,90.000000,91.600000,95.400000
std,0.875595,4.98999,5.202563,5.416026,4.376706,2.988868
min,20.000000,81.00000,78.000000,79.000000,85.000000,91.000000
25%,20.250000,85.25000,84.500000,87.250000,88.500000,93.250000
50%,21.000000,88.50000,88.500000,90.500000,90.500000,95.500000
75%,22.000000,91.50000,90.750000,92.750000,94.500000,97.500000
max,22.000000,97.00000,95.000000,98.000000,99.000000,100.000000