In [162]:
import pandas as pd

In [163]:
df = pd.read_csv("student_performance.csv")

In [164]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        20 non-null     str
 1   Name              20 non-null     str
 2   Age               20 non-null     int64
 3   Program           20 non-null     str
 4   Python            20 non-null     int64
 5   Mathematics       20 non-null     int64
 6   Statistics        20 non-null     int64
 7   Machine_Learning  20 non-null     int64
 8   Attendance        20 non-null     int64
dtypes: int64(6), str(3)
memory usage: 1.5 KB

In [165]:
df.head()

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance
0,S001,Ali Khan,20,AI,85,78,92,88,95
1,S002,Sara Ahmed,21,AI,72,75,70,80,90
2,S003,Ahmed Raza,22,SE,90,88,91,93,96
3,S004,Fatima Noor,20,DS,65,70,68,72,85
4,S005,Usman Ali,21,AI,78,82,80,76,88

In [166]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Program', 'Python', 'Mathematics',
       'Statistics', 'Machine_Learning', 'Attendance'],
      dtype='str')

In [167]:
subject_marks = df.drop(columns=['Student_ID', 'Name', 'Age', 'Program', 'Attendance'])

In [168]:
subject_marks

    Python  Mathematics  Statistics  Machine_Learning
0       85           78          92                88
1       72           75          70                80
2       90           88          91                93
3       65           70          68                72
4       78           82          80                76
5       95           94          96                97
6       55           60          58                62
7       88           86          90                91
8       73           77          75                79
9       81           84          79                85
10      69           71          74                70
11      92           90          93                95
12      76           74          78                80
13      84           83          86                88
14      61           65          63                67
15      89           91          88                90
16      74           72          76                78
17      97           95          98                99
18      68           66          70                72
19      86           89          87                90

In [169]:
average_marks = subject_marks.mean().to_dict()
average_marks

{'Python': 78.9,
 'Mathematics': 79.5,
 'Statistics': 80.6,
 'Machine_Learning': 82.6}

In [170]:
df['Total Marks'] = subject_marks.sum(axis=1)
subject_marks['Total Marks'] = subject_marks.sum(axis=1)

In [171]:
subject_marks

    Python  Mathematics  Statistics  Machine_Learning  Total Marks
0       85           78          92                88          343
1       72           75          70                80          297
2       90           88          91                93          362
3       65           70          68                72          275
4       78           82          80                76          316
5       95           94          96                97          382
6       55           60          58                62          235
7       88           86          90                91          355
8       73           77          75                79          304
9       81           84          79                85          329
10      69           71          74                70          284
11      92           90          93                95          370
12      76           74          78                80          308
13      84           83          86                88          341
14      61           65          63                67          256
15      89           91          88                90          358
16      74           72          76                78          300
17      97           95          98                99          389
18      68           66          70                72          276
19      86           89          87                90          352

In [172]:
df

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance,Total Marks
0,S001,Ali Khan,20,AI,85,78,92,88,95,343
1,S002,Sara Ahmed,21,AI,72,75,70,80,90,297
2,S003,Ahmed Raza,22,SE,90,88,91,93,96,362
3,S004,Fatima Noor,20,DS,65,70,68,72,85,275
4,S005,Usman Ali,21,AI,78,82,80,76,88,316
5,S006,Ayesha Malik,22,SE,95,94,96,97,99,382
6,S007,Hassan Tariq,20,DS,55,60,58,62,75,235
7,S008,Zainab Iqbal,21,AI,88,86,90,91,94,355
8,S009,Bilal Ahmed,23,SE,73,77,75,79,82,304
9,S010,Maryam Khan,20,DS,81,84,79,85,91,329
10,S011,Hamza Siddiqui,22,AI,69,71,74,70,87,284
11,S012,Noor Fatima,21,SE,92,90,93,95,98,370
12,S013,Talha Javed,20,DS,76,74,78,80,89,308
13,S014,Iqra Aslam,22,AI,84,83,86,88,92,341
14,S015,Danish Ali,23,SE,61,65,63,67,78,256
15,S016,Hira Shah,21,DS,89,91,88,90,96,358
16,S017,Omar Farooq,20,AI,74,72,76,78,84,300
17,S018,Laiba Khan,22,SE,97,95,98,99,100,389
18,S019,Abdullah,21,DS,68,66,70,72,80,276
19,S020,Mehwish,20,AI,86,89,87,90,93,352

In [173]:
top_five_students = df.sort_values("Total Marks", ascending=False).head()

In [174]:
top_five_students

,Student_ID,Name,Age,Program,Python,Mathematics,Statistics,Machine_Learning,Attendance,Total Marks
17,S018,Laiba Khan,22,SE,97,95,98,99,100,389
5,S006,Ayesha Malik,22,SE,95,94,96,97,99,382
11,S012,Noor Fatima,21,SE,92,90,93,95,98,370
2,S003,Ahmed Raza,22,SE,90,88,91,93,96,362
15,S016,Hira Shah,21,DS,89,91,88,90,96,358

In [175]:
average_marks

{'Python': 78.9,
 'Mathematics': 79.5,
 'Statistics': 80.6,
 'Machine_Learning': 82.6}

In [176]:
for subject in average_marks:
    low_scorers = (subject_marks.loc[subject_marks[subject] < average_marks[subject]].index.tolist())
    print("Students scoring below average in", subject, "are:\n", df.loc[low_scorers,['Student_ID','Name', subject]], "\n")

Students scoring below average in Python are:
    Student_ID            Name  Python
1        S002      Sara Ahmed      72
3        S004     Fatima Noor      65
4        S005       Usman Ali      78
6        S007    Hassan Tariq      55
8        S009     Bilal Ahmed      73
10       S011  Hamza Siddiqui      69
12       S013     Talha Javed      76
14       S015      Danish Ali      61
16       S017     Omar Farooq      74
18       S019        Abdullah      68

Students scoring below average in Mathematics are:
    Student_ID            Name  Mathematics
0        S001        Ali Khan           78
1        S002      Sara Ahmed           75
3        S004     Fatima Noor           70
6        S007    Hassan Tariq           60
8        S009     Bilal Ahmed           77
10       S011  Hamza Siddiqui           71
12       S013     Talha Javed           74
14       S015      Danish Ali           65
16       S017     Omar Farooq           72
18       S019        Abdullah           66

Students scoring below average in Statistics are:
    Student_ID            Name  Statistics
1        S002      Sara Ahmed          70
3        S004     Fatima Noor          68
4        S005       Usman Ali          80
6        S007    Hassan Tariq          58
8        S009     Bilal Ahmed          75
9        S010     Maryam Khan          79
10       S011  Hamza Siddiqui          74
12       S013     Talha Javed          78
14       S015      Danish Ali          63
16       S017     Omar Farooq          76
18       S019        Abdullah          70

Students scoring below average in Machine_Learning are:
    Student_ID            Name  Machine_Learning
1        S002      Sara Ahmed                80
3        S004     Fatima Noor                72
4        S005       Usman Ali                76
6        S007    Hassan Tariq                62
8        S009     Bilal Ahmed                79
10       S011  Hamza Siddiqui                70
12       S013     Talha Javed                80
14       S015      Danish Ali                67
16       S017     Omar Farooq                78
18       S019        Abdullah                72

In [177]:
df['Total Marks'].mean()

np.float64(321.6)

In [178]:
print("Students scoring below average overall:")
low_scorers = df.loc[df['Total Marks'] < df['Total Marks'].mean(), ['Student_ID','Name','Total Marks']]
low_scorers

Students scoring below average overall:

   Student_ID            Name  Total Marks
1        S002      Sara Ahmed          297
3        S004     Fatima Noor          275
4        S005       Usman Ali          316
6        S007    Hassan Tariq          235
8        S009     Bilal Ahmed          304
10       S011  Hamza Siddiqui          284
12       S013     Talha Javed          308
14       S015      Danish Ali          256
16       S017     Omar Farooq          300
18       S019        Abdullah          276

In [179]:
print(len(df))  # total no of students

20

In [181]:
low_scorers.to_csv('low_scorers.csv', index=False)
top_five_students.to_csv('top_five_students.csv', index=False)
df.to_csv('record_with_totals.csv', index=False)